### ISSUE TITLE
Kualitas video kosong

### ISSUE THREAD

**Issue by amrulizwan** [RizkyFauziIlmi/Anime-API#5]
ini kualitas videonya emang kosong atau gimana mas?
    "mirror1": {
        "quality": "360p",
        "mirrorList": []
    },
    "mirror2": {
        "quality": "480p",
        "mirrorList": [
            {
                "host": "moedesu",
                "id": "#"
            },
            {
                "host": "odstream",
                "id": "#"
            },
            {
                "host": "mp4load",
                "id": "#"
            },
            {
                "host": "mega",
                "id": "#"
            }
        ]
    },
    "mirror3": {
        "quality": "720p",
        "mirrorList": [
            {
                "host": "moedesuhd",
                "id": "#"
            },
            {
                "host": "odstreamhd",
                "id": "#"
            },
            {
                "host": "yourupload",
                "id": "#"
            },
            {
                "host": "mega",
                "id": "#"
            }
        ]
    },

**Comment by RizkyFauziIlmi** [comment]
kayaknya ada yang berubah di element html websitenya, nanti saya benerin pas senggang. mohon di tunggu

**Comment by RizkyFauziIlmi** [comment]
setelah saya cek ternyata API ini belum bisa mengambil stream dari mirror yang lain dikarenakan untuk mengakses stream yang lain perlu meng click list terlebih dahulu agar src video berubah, untuk sekarang project ini belum support web automation jadi mirror belum ada isi link stream nya. semoga menjawab @amrulizwan
